services:
  postgres:
    image: postgres:15-alpine
    container_name: decentkids_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: decentkids_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: decentkids@123
    ports:
      - "5433:5432"
    volumes:
      - decentkids_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d decentkids_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: decentkids_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@decentkids.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  decentkids_pgdata:
